name: 'Monolith Compile and Upload'
description: 'Monolith Compile and Upload action'

inputs:
  github_ref_name:
    description: 'GitHub ref_name property'
    required: true
  github_sha:
    description: 'GitHub sha property'
    required: true
  s3_bucket:
    description: 'S3 Bucket name'
    required: true
  s3_folder:
    description: 'S3 Folder name. Optional'
    required: false
  compile_app:
    description: 'Specific app such as care, eapi, signup or default'
    required: false
    default: ''
  rebuild:
    description: 'Rebuild always. Default true'
    required: false
    default: true
  custom_access_token:
    description: 'AWS Custom GitHub Access Token'
    required: true
  aws_access_key:
    description: 'AWS Access Key (Required if no aws-actions/configure-aws-credentials)'
    required: true
  aws_secret_key:
    description: 'AWS Secret Key (Required if no aws-actions/configure-aws-credentials)'
    required: true
  aws_region:
    description: 'AWS Region'
    required: false
    default: 'us-east-1'

runs:
  using: 'composite'
  steps:
    - name: Determine Compile App
      id: app
      shell: powershell
      run: |
        Switch ("${{ inputs.compile_app }}")
        {
            "care" {
              $compiled_folder = "Care"
              $deploy_folder = "care"
            }
            "eapi" {
              $compiled_folder = "External.Api"
              $deploy_folder = "external_api"
            }
            "signup" {
              $compiled_folder = "Suite.Signup"
              $deploy_folder = "signup"
            }
            default {
              $compiled_folder="*"
              $deploy_folder="appdev"
            }
        }

        echo "Compiled folder = $compiled_folder Deploy folder = $deploy_folder"

        "compiled_folder=$compiled_folder" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        "deploy_folder=$deploy_folder" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name: Extract branch name
      id: extract_branch
      shell: powershell
      run: |
        $branch = "${{ inputs.github_ref_name }}"
        $clean_branch = $branch.ToLower() -replace '_','' | Out-String
        if ($branch.Length -gt 38) {
          $clean_branch = $clean_branch.SubString(0,38)
        }
        "CLEAN_BRANCH=$clean_branch" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name: Determine Monolith Compile
      id: monolith
      shell: powershell
      run: |
        echo "Determine monolith compile or download existing zip"
        $compile = "${{ inputs.rebuild }}"
        
        if ($compile -eq "false") {
          
          $bucketName = "${{ inputs.s3_bucket }}"
          $filePath = "${{ steps.extract_branch.outputs.CLEAN_BRANCH }}.zip"

          echo "Check if file exists on S3 $bucketName $filePath"
          
          $exists=aws s3 ls s3://$bucketName/$filePath 2>&1
          if ($exists -eq $null) {
            echo "File not found, recompile."  
            $compile = "true"
          }
            
          $zip = Get-S3Object -BucketName $bucketName -Key $filePath

          if ($zip -eq $null) {
            echo "File not found, recompile."  
            $compile = "true"
          }
        }
        "compile=$compile" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name: Authenticate with Dev
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key }}
        aws-secret-access-key: ${{ inputs.aws_secret_key }}
        aws-region: ${{ inputs.aws_region }}

    - name: Download file form S3      
      if: ${{ steps.monolith.outputs.compile == 'false' }}
      shell: powershell
      run: |
        echo "Download file from S3"
        $aws_path = "${{ inputs.s3_bucket }}"
        $branch = "${{ steps.extract_branch.outputs.CLEAN_BRANCH }}"

        aws s3 cp s3://$aws_path/$branch.zip .\build.zip
        $progressPreference = 'SilentlyContinue'

    - name: Decompress zip File
      if: ${{ steps.monolith.outputs.compile == 'false' }}
      run: Expand-Archive -Path .\build.zip -DestinationPath . -Force
      shell: powershell     

    - name: Monolith Code
      uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of sonarqube reporting
        fetch-depth: 1     

    - name: Install VSSetup PowerShell Module
      shell: pwsh
      run: |
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
        Install-Module VSSetup -Scope CurrentUser -Force -AllowClobber

    - name: Read back values
      shell: powershell        
      run: |
        $compiled_folder = "${{ steps.app.outputs.compiled_folder }}"
        $deploy_folder = "${{ steps.app.outputs.deploy_folder }}"
        $branch = "${{ steps.extract_branch.outputs.CLEAN_BRANCH }}"

        echo "Branch $branch is using PatriotSoftware.$compiled_folder.Compiled"
        echo "Work directory C:\actions-runner\_work\PatriotSoftware\PatriotSoftware\aws\$deploy_folder\deploy"
  
    - name: Copy NuGet
      if: ${{ steps.monolith.outputs.compile == 'true' }} 
      shell: powershell
      run: aws s3 cp s3://dev-ci-nuget-config/NuGet.Config "C:\Program Files (x86)\NuGet\Config\NuGet.config"
    
    - name: Restore nuget packages
      if: ${{ steps.monolith.outputs.compile == 'true' }} 
      shell: powershell
      run: nuget restore src\PatriotSoftware.sln -Verbosity quiet

    - name: Compile
      if: ${{ steps.monolith.outputs.compile == 'true' }}
      shell: powershell
      run: .\build2.bat compile
   
    - name: Copy abcpdf8-32
      if: ${{ steps.monolith.outputs.compile == 'true' }} 
      shell: powershell
      run: |
        Get-ChildItem -Path artifacts -Recurse -Directory -Force -ErrorAction SilentlyContinue | Select-Object FullName
        .\build2.bat copy_extra_assemblies

    - name: Precompile Websites
      if: ${{ steps.monolith.outputs.compile == 'true' }}
      shell: powershell
      run: .\build2.bat precompile_websites

    - name: Transform All Configs
      if: ${{ steps.monolith.outputs.compile == 'true' }}
      shell: powershell
      run: .\build2.bat transform_all_configs

    - name: AwsDeploy Code
      uses: actions/checkout@v4      
      with:
        repository: SynergyDataSystems/PatriotSoftware.AwsDeploy
        token: ${{ inputs.custom_access_token }}
        path: .\aws

    - name: Combine AwsDeploy with Monolith code
      id: aws-work
      run: |
        $deploy_folder = "${{ steps.app.outputs.deploy_folder }}"
        echo "Deploy folder: $deploy_folder"

        $work_dir = "C:\actions-runner\_work\PatriotSoftware\PatriotSoftware\aws\deploy\$deploy_folder\deploy"
      
        echo "Work dir = $work_dir"

        mkdir $work_dir\wwwroot
        (Get-Content $work_dir\install_script.ps1).Replace('dev_folder_name = "master"', 'dev_folder_name = "${{ steps.extract_branch.outputs.CLEAN_BRANCH }}"') | Set-Content $work_dir\install_script.ps1    

        "work_dir=$work_dir" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append       
      shell: powershell

    - name: Copy Compiled Folder(s) from local
      if: ${{ steps.monolith.outputs.compile == 'true' }}
      run: |
        $compiled_folder = "${{ steps.app.outputs.compiled_folder }}"
        $work_dir = "${{ steps.aws-work.outputs.work_dir }}"

        echo "Using PatriotSoftware.$compiled_folder.Compiled"
        Copy-Item -Path artifacts\PublishedWebsites\PatriotSoftware.$compiled_folder.Compiled -Destination $work_dir\wwwroot -Recurse
      shell: powershell

    - name: Copy Compiled Folder(s) from zip
      if: ${{ steps.monolith.outputs.compile == 'false' }}
      run: |
        $compiled_folder = "${{ steps.app.outputs.compiled_folder }}"
        $work_dir = "${{ steps.aws-work.outputs.work_dir }}"

        echo "Using PatriotSoftware.$compiled_folder.Compiled"
        Copy-Item -Path deploy\wwwroot\PatriotSoftware.$compiled_folder.Compiled -Destination $work_dir\wwwroot -Recurse
      shell: powershell

    - name: Zip File Name
      id: filename
      run: |
        $branch = "${{ steps.extract_branch.outputs.CLEAN_BRANCH }}"
        $deploy_folder = "${{ steps.app.outputs.deploy_folder }}"
                
        if ( $branch -eq "main" -Or $branch -eq "master" ) {
          echo "Main branch, using github sha 10-digits"
          $branch = ("${{ inputs.github_sha }}").SubString(0,10)
        }

        if ( $deploy_folder -ne "appdev") {
          echo "Using prefix app on zip file"
          $branch = "$deploy_folder" + "_" + "$branch"
        }

        "name=$branch" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
      shell: powershell

    - name: Zip File Path
      id: aws_path
      run: |        
        $aws_path = "${{ inputs.s3_bucket }}"
        $s3folder = "${{ inputs.s3_folder }}"
        if (![string]::IsNullOrEmpty($s3folder)) {
          echo "Using s3 folder provided"
          $aws_path += "/" + $s3folder
        }

        "path=$aws_path" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
      shell: powershell

    - name: Upload Artifact Zip to Dev
      run: |        
        $filename = "${{ steps.filename.outputs.name }}"
        $aws_path = "${{ steps.aws_path.outputs.path }}"
        $deploy_folder = "${{ steps.app.outputs.deploy_folder }}"
        
        $compress = @{
          Path = "C:\actions-runner\_work\PatriotSoftware\PatriotSoftware\aws\deploy\$deploy_folder\*"
          CompressionLevel = "Fastest"
          DestinationPath = "C:\artifacts\tests.zip"
        }
        mkdir c:\artifacts
        Compress-Archive @compress
        
        echo "Copying to s3://$aws_path/${filename}.zip"
        aws s3 cp "C:\artifacts\tests.zip" s3://$aws_path/$filename.zip
      shell: powershell
