name: 'Monolith Compile and Upload'
description: 'Monolith Compile and Upload action'

inputs:
  github_ref_name:
    description: 'GitHub ref_name property'
    required: true
  github_sha:
    description: 'GitHub sha property'
    required: true
  s3_bucket:
    description: 'S3 Bucket name'
    required: true
  s3_folder:
    description: 'S3 Folder name. Optional'
    required: false
  app_compiled_folder:
    description: 'Specific application folder: PatriotSoftware.{name}.Compiled'
    required: false
    default: '*'
  custom_access_token:
    description: 'AWS Custom GitHub Access Token'
    required: true
  aws_access_key:
    description: 'AWS Access Key (Required if no aws-actions/configure-aws-credentials)'
    required: true
  aws_secret_key:
    description: 'AWS Secret Key (Required if no aws-actions/configure-aws-credentials)'
    required: true
  aws_region:
    description: 'AWS Region'
    required: false
    default: 'us-east-1'

runs:
  using: 'composite'
  steps:
    - name: Monolith Code
      uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of sonarqube reporting
        fetch-depth: 1     

    - name: Java Install
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
      
    - name: Dev Authenticate
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key }}
        aws-secret-access-key: ${{ inputs.aws_secret_key }}
        aws-region: ${{ inputs.aws_region }}
  
    - name: Copy NuGet 
      shell: powershell
      run: aws s3 cp s3://dev-ci-nuget-config/NuGet.Config "C:\Program Files (x86)\NuGet\Config\NuGet.config"
    
    - name: Restore nuget packages 
      shell: powershell
      run: nuget restore src\PatriotSoftware.sln -Verbosity quiet
      
    - name: Build and analyze
      shell: powershell
      run: |
        $base_dir = "C:\actions-runner\_work\PatriotSoftware\PatriotSoftware\artifacts"
        $bin_dir = "$base_dir\bin"	
        mkdir $bin_dir
        msbuild src\PatriotSoftware.sln /m /p:Platform="x64" /t:Rebuild /p:Configuration="Dev" /p:OutDir="$bin_dir" /p:ExeProjectOutputDir="$base_dir\ScheduledTasks"
        mv "$bin_dir\_PublishedWebsites" "$base_dir\PublishedWebsites"
        
    - name: Copy abcpdf8-32 
      shell: powershell
      run: |
        Get-ChildItem -Path artifacts -Recurse -Directory -Force -ErrorAction SilentlyContinue | Select-Object FullName
        .\build2.bat copy_extra_assemblies

    - name: Precompile websites 
      shell: powershell
      run: |           
        Import-Module '.\build\tools\psake\psake.psm1'
        $psake.use_exit_on_error = $true
        Invoke-psake .\build\build2.ps1 precompile_websites 

    - name: AwsDeploy Code
      uses: actions/checkout@v4
      with:
        repository: SynergyDataSystems/PatriotSoftware.AwsDeploy
        token: ${{ inputs.custom_access_token }}
        path: .\deploy\appdev

    - name: Extract branch name
      id: extract_branch
      shell: powershell
      run: |
        $branch = "${{ inputs.github_ref_name }}"
        $clean_branch = $branch.ToLower() -replace '_','' | Out-String
        if ($branch.Length -gt 38) {
          $clean_branch = $clean_branch.SubString(0,38)
        }
        "CLEAN_BRANCH=$clean_branch" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name: Combine AwsDeploy with Monolith code
      env:
        dev_folder_name: ${{ steps.extract_branch.outputs.CLEAN_BRANCH }}
      run: |
        $work_dir = "C:\actions-runner\_work\PatriotSoftware\PatriotSoftware\deploy\appdev\deploy\appdev\deploy"
        mkdir $work_dir\wwwroot
        (Get-Content $work_dir\install_script.ps1).Replace('dev_folder_name = "master"', 'dev_folder_name = "$dev_folder_name"') | Set-Content $work_dir\install_script.ps1
        Copy-Item -Path artifacts\PublishedWebsites\${{ inputs.app_compiled_folder }}.Compiled -Destination $work_dir\wwwroot -Recurse    
      shell: powershell  

    - name: Zip File Name
      id: filename
      run: |
        $branch = "${{ steps.extract_branch.outputs.CLEAN_BRANCH }}"
                
        if ( $branch -eq "main" -Or $branch -eq "master" ) {
          echo "Main branch, using github sha 10-digits"
          $branch = ("${{ inputs.github_sha }}").SubString(0,10)
        }

        "name=$branch" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
      shell: powershell

    - name: Zip File Path
      id: aws_path
      run: |        
        $aws_path = "${{ inputs.s3_bucket }}"
        $s3folder = "${{ inputs.s3_folder }}"
        if (![string]::IsNullOrEmpty($s3folder)) {
          echo "Using s3 folder provided"
          $aws_path += "/" + $s3folder
        }

        "path=$aws_path" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
      shell: powershell

    - name: Upload Artifact Zip to Dev   
      run: |        
        $filename = "${{ steps.filename.outputs.name }}"
        $aws_path = "${{ steps.aws_path.outputs.path }}"

        $compress = @{
          Path = "C:\actions-runner\_work\PatriotSoftware\PatriotSoftware\deploy\appdev\deploy\appdev\*"
          CompressionLevel = "Fastest"
          DestinationPath = "C:\artifacts\tests.zip"
        }
        mkdir c:\artifacts
        Compress-Archive @compress
        
        echo "Copying to s3://$aws_path/${filename}.zip"
        aws s3 cp "C:\artifacts\tests.zip" s3://$aws_path/$filename.zip
      shell: powershell
